#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - unzip
  - php5
  - php5-mysql
  - apache2
  - mysql-server
  - imagemagick
runcmd:
  - echo -n "127.0.1.1 ">>/etc/hosts
  - cat /etc/hostname>>/etc/hosts
  - ["cd","/tmp"]
  - ["git","clone","https://github.com/cgeroux/cloud-init-omeka.git"]
#  - ["/tmp/cloud-init-omeka/omeka-setup.py "]

